config/routes.rb
Rails.application.routes.draw do
  get 'basesectors/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'logins#index'
  resources :dealts
  resources :clas
  resources :unionsectors do
    collection do
      post 'get_user_list'
    end
  end
  resources :basesectors do
    collection do
      post 'get_user_list'
    end
  end
  resources :users do
    collection do
      get 'checkuser'
      get 'checkauth'
    end
  end
  resources :flowtemplates
  resources :flowdefs do
    member do
       get 'del_wordtype'
      get 'up_wordtype'
      get 'down_wordtype'
    end
  end
  resources :flows do
    collection do
      post 'uploadfile'
      get 'get_attachments'
      get 'del_attachment'
    end
  end
  resources :logins do
    collection do
      get 'logout'
    end
  end
  resources :modpwds
  resources :usergroups
  resources :myflows
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :flowattachment
  has_attached_file :attachment, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :attachment
end

app/models/auth.rb
class Auth < ApplicationRecord
  has_and_belongs_to_many :usergroups
end

app/models/basesector.rb
class Basesector < ApplicationRecord
  has_many :users
end

app/models/cla.rb
class Cla < ApplicationRecord
  has_many :flowtemplates
  has_many :unionsectors
end

app/models/dropdown.rb
class Dropdown < ApplicationRecord
  has_many :dropdownoptions
  belongs_to :flowtemplate
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :flow
  belongs_to :user
end

app/models/flow.rb
class Flow < ApplicationRecord
  has_many :flowdetails
  belongs_to :flowdef,optional: true
  has_many :flowfloats
  has_many :flowstrings
  has_many :flowtexts
  has_many :flowattachments
  has_many :flowints
  has_many :opinions
  has_many :feedbacks
  accepts_nested_attributes_for :feedbacks, allow_destroy: true
end

app/models/flowdef.rb
class Flowdef < ApplicationRecord
  has_many :wordtypes
  accepts_nested_attributes_for :wordtypes, allow_destroy: true
  has_many :flows
  belongs_to :unionsector
end

app/models/flowfloat.rb
class Flowfloat < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/flowint.rb
class Flowint < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/flowtext.rb
class Flowtext < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/grant.rb
class Grant < ApplicationRecord
  belongs_to :user
  belongs_to :flowtemplate
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :flow
  belongs_to :user
end

app/models/unionsector.rb
class Unionsector < ApplicationRecord
  has_many :users
  belongs_to :cla
  has_many :flowdefs
end

app/models/user.rb
class User < ApplicationRecord
  has_many :grants
  belongs_to :basesector, optional: true
  belongs_to :unionsector, optional: true
  belongs_to :basesector, optional: true
  has_many :usergroups
  has_many :opinions
  has_many :feedbacks
  has_and_belongs_to_many :usergroups
  has_many :userbusinadmins
  has_many :userfeedadmins
  has_secure_password
end

app/models/usergroup.rb
class Usergroup < ApplicationRecord
  has_and_belongs_to_many :auths
  has_and_belongs_to_many :users
end

app/models/wordattch.rb
class Wordattch < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordcoin.rb
class Wordcoin < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordint.rb
class Wordint < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordtext.rb
class Wordtext < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordtype.rb
class Wordtype < ApplicationRecord
  belongs_to :flowdef
  belongs_to :wordtypedef, optional: true
  default_scope { order('corder') }
end

app/controllers/unionsectors_controller.rb
class UnionsectorsController < ApplicationController
  before_action :set_unionsector, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => :get_user_list
  def index
    @unionsectors = Unionsector.all
  end

  def show
  end

  def new
    @unionsector = Unionsector.new
  end

  def edit
  end

  def create
    @unionsector = Unionsector.new(unionsector_params)
    respond_to do |format|
      if @unionsector.save
        format.html { redirect_to unionsectors_path, notice: 'Unionsector was successfully created.' }
        format.json { render :show, status: :created, location: @unionsector }
      else
        format.html { render :new }
        format.json { render json: @unionsector.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @unionsector.update(unionsector_params)
        format.html { redirect_to unionsectors_path, notice: 'Unionsector was successfully updated.' }
        format.json { render :show, status: :ok, location: @unionsector }
      else
        format.html { render :edit }
        format.json { render json: @unionsector.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    users = @unionsector.users
    if users.count == 0
      @unionsector.destroy
      redirect_to unionsectors_path
    else
      respond_to do |format|
        format.html { redirect_to unionsectors_path, notice: '1' }
      end
    end

      #redirect_to unionsectors_path
  end

  def get_user_list
    unionsector = Unionsector.find(params[:unionsector_id])
    @users = unionsector.users
    render(partial: 'get_user_list', locals:  {object: @users}, formats:[:js] )

  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_unionsector
    @unionsector = Unionsector.find(params[:id])
  end

  def unionsector_params
    params.require(:unionsector).permit(:cla_id, :name, :tel, :summary)
  end
end

app/helpers/unionsectors_helper.rb
module UnionsectorsHelper
end

app/views/unionsectors/_form.html.erb
<div class="alert alert-block alert-success" style="display:none;">
  <button type="button" class="close" data-dismiss="alert">
    <i class="icon-remove"></i>
  </button>

  <p>
    <strong>
      <i class="icon-ok"></i>
    </strong>
    保存成功
  </p>

</div>

<%= form_with(model:unionsector,local:true,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
    <h3 class="header smaller lighter blue">
部门
      <small></small>
    </h3>
  <div class="form-group">
    <label class="col-sm-2 control-label no-padding-right" for="form-field-1"> 部门分类 </label>
    <div class="col-sm-10">
      <%= f.select :cla_id,Cla.all.map{|p| [p.name,p.id]},{include_blank:'请选择部门'},class:"col-xs-10 col-sm-8" %>
    </div>
  </div>
    <div class="form-group">
      <label class="col-sm-2 control-label no-padding-right" for="form-field-1"> 部门名称 </label>
      <div class="col-sm-10">
        <%= f.text_field :name,class:"col-xs-10 col-sm-8" %>
      </div>
    </div>
  <div class="form-group">
    <label class="col-sm-2 control-label no-padding-right" for="form-field-1"> 电话 </label>
    <div class="col-sm-10">
      <%= f.text_field :tel,class:"col-xs-10 col-sm-8" %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label no-padding-right" for="form-field-1"> 描述 </label>
    <div class="col-sm-10">
      <%= f.text_area :summary,class:"col-xs-10 col-sm-8" %>
    </div>
  </div>

    <div class="clearfix form-actions">
      <div class="col-md-offset-2 col-md-10">
        <button type="submit" name="commit" value="保存" class="btn btn-info" data-disable-with="保存" id="submit">
          <i class="icon-ok bigger-110"></i>
          保存
        </button>

      </div>
    </div>
<% end %>

app/views/unionsectors/_users.html.erb
<div class="widget-body">
  <div class="widget-main padding-8">
    <div class="profile-feed">

      <% @users.each do |user| %>
        <div class="profile-activity clearfix">
          <div>
            <div class="col-md-6">
              <% if user.sex == 1 || user.sex.to_s == '' %>
              <h4 class="blue"><i class="fa fa-user-o"></i> <%= user.name %> </h4>
                <% else %>
                <h4 class="purple"><i class="fa fa-user-o"></i> <%= user.name %> </h4>
                <% end %>
            </div>

            <div class="col-md-6 text-right">
              <h5 class=""> <%= user.offer %> </h5>
            </div>
            <div class="time col-md-12">
              <i class="fa fa-phone"></i>
              <%= user.phone %>
            </div>
          </div>
          <div class="tools action-buttons">
            <a href=<%= edit_user_path(user) %> class="blue userclick">
              <i class="icon-pencil bigger-125"></i>
            </a>
              <a data-confirm="确认删除?" data-method="delete" class="red" href=<%= user_path(user,callback:'unionsector') %>>
              <i class="icon-remove bigger-125"></i>
            </a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  '<% session[:callback]='unionsector' %>'
    '<% session[:selectid]=params[:selectid] %>'
</script>

app/views/unionsectors/edit.html.erb
<%= render 'layerbegin' %>
<div class="page-content">


  <div class="row">
    <div class="col-xs-12">
      <%= render 'form', unionsector: @unionsector %>
    </div>
  </div>
</div>
<%= render 'layerend' %>

app/views/unionsectors/index.html.erb
<%= render 'layerbegin' %>

<style>
  .select-backcolor{
    background-color: #f4f9fd;
  }
</style>

<div class="alert alert-block alert-danger" style="display:none;">
  <button type="button" class="close" data-dismiss="alert">
    <i class="icon-remove"></i>
  </button>

  <p>
    <strong>
      <i class="fa fa-close"></i>
    </strong>
    该部门下存在用户，无法删除！
  </p>

</div>

<% if notice && notice =='1'  %>
  <script>
      $('.alert-danger').show();
  </script>
<% end %>

<div class="page-content">
  <div class="page-header">
    <h1>
      部门
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->
      <div class="widget-box transparent col-lg-6">
        <div class="widget-header widget-header-small">
          <h4 class="blue smaller">
            <i class="fa fa-bank orange"></i>
          </h4>
          <div class="widget-toolbar action-buttons">
            <a href=<%= new_unionsector_path %>>
              <i class="icon-plus blue"></i>
            </a>
            &nbsp;&nbsp;
          </div>
        </div>

        <div class="widget-body">
          <div class="widget-main padding-8">
            <div class="profile-feed">
              <% @unionsectors.each do |unionsector| %>
                <div class="profile-activity clearfix unioncla" value=<%= unionsector.id %>>
                  <div>
                    <h4 class="blue"> <%= unionsector.name %> </h4>
                    <div class="time">
                      <i class="fa fa-phone"></i>
                      <%= unionsector.tel %>
                    </div>
                    <div class="time">&nbsp;&nbsp;&nbsp;
                      <%= unionsector.summary %>
                    </div>
                  </div>
                  <div class="tools action-buttons">
                    <a href=<%= edit_unionsector_path(unionsector) %> class="blue">
                      <i class="icon-pencil bigger-125"></i>
                    </a>
                    <a data-confirm="确认删除?" data-method="delete" class="red" href=<%= unionsector_path(unionsector) %>>
                      <i class="icon-remove bigger-125"></i>
                    </a>
                  </div>
                </div>
              <% end %>

            </div>
          </div>
        </div>
      </div>

      <div class="widget-box transparent col-lg-6">
        <div class="widget-header widget-header-small">
          <h4 class="blue smaller">
            <i class="fa fa-user blue"></i>
          </h4>
          <div class="widget-toolbar action-buttons">
            <a id = 'newuser' href=<%= new_user_path(callback:'unionsector') %>>
              <i class="icon-plus blue"></i>
            </a>
          </div>
        </div>
        <input type="hidden" id="selectid">
        <div id ='userdiv'>

        </div>


      </div>

      <script>
          $(document).ready(function () {
              (function ($) {
                  $.getUrlParam = function (name) {
                      var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)");
                      var r = window.location.search.substr(1).match(reg);
                      if (r != null) return unescape(r[2]); return null;
                  }
              })(jQuery);
              var currentpart = 0;
              if($.getUrlParam('selectid')){
                  currentpart = $.getUrlParam('selectid');
                  $('.unioncla').each(function () {
                      if($(this).attr('value')==currentpart){
                          $(this).addClass('select-backcolor');
                      }
                  });
                  $.post("unionsectors/get_user_list",
                      {
                          unionsector_id:currentpart
                      }
                  );
              }
              $('.unioncla').click(function () {
                  $('.unioncla').each(function () {
                      $(this).removeClass('select-backcolor');
                  });
                  $(this).addClass('select-backcolor');
                  currentpart = $(this).attr('value');
                  $('#newuser').attr('href','users/new?callback=unionsector&selectid='+currentpart);
                  $.post("unionsectors/get_user_list",
                      {
                          unionsector_id:currentpart
                      }
                  );
              });
          });

      </script>


<%= render 'layerend' %>

app/views/unionsectors/new.html.erb
<%= render 'layerbegin' %>
<div class="page-content">


  <div class="row">
    <div class="col-xs-12">
      <%= render 'form', unionsector: @unionsector %>
    </div>
  </div>
</div>
<%= render 'layerend' %>