config/routes.rb
Rails.application.routes.draw do
  get 'basesectors/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'logins#index'
  resources :dealts
  resources :clas
  resources :unionsectors do
    collection do
      post 'get_user_list'
    end
  end
  resources :basesectors do
    collection do
      post 'get_user_list'
    end
  end
  resources :users do
    collection do
      get 'checkuser'
      get 'checkauth'
    end
  end
  resources :flowtemplates
  resources :flowdefs do
    member do
       get 'del_wordtype'
      get 'up_wordtype'
      get 'down_wordtype'
    end
  end
  resources :flows do
    collection do
      post 'uploadfile'
      get 'get_attachments'
      get 'del_attachment'
    end
  end
  resources :logins do
    collection do
      get 'logout'
    end
  end
  resources :modpwds
  resources :usergroups
  resources :myflows
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :flowattachment
  has_attached_file :attachment, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :attachment
end

app/models/auth.rb
class Auth < ApplicationRecord
  has_and_belongs_to_many :usergroups
end

app/models/basesector.rb
class Basesector < ApplicationRecord
  has_many :users
end

app/models/cla.rb
class Cla < ApplicationRecord
  has_many :flowtemplates
  has_many :unionsectors
end

app/models/dropdown.rb
class Dropdown < ApplicationRecord
  has_many :dropdownoptions
  belongs_to :flowtemplate
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :flow
  belongs_to :user
end

app/models/flow.rb
class Flow < ApplicationRecord
  has_many :flowdetails
  belongs_to :flowdef,optional: true
  has_many :flowfloats
  has_many :flowstrings
  has_many :flowtexts
  has_many :flowattachments
  has_many :flowints
  has_many :opinions
  has_many :feedbacks
  accepts_nested_attributes_for :feedbacks, allow_destroy: true
end

app/models/flowdef.rb
class Flowdef < ApplicationRecord
  has_many :wordtypes
  accepts_nested_attributes_for :wordtypes, allow_destroy: true
  has_many :flows
  belongs_to :unionsector
end

app/models/flowdetail.rb
class Flowdetail < ApplicationRecord
  belongs_to :flow
  has_many :flowfloats
  has_many :flowstrings
  has_many :flowtexts
  has_many :flowattachments
  has_many :flowints
end

app/models/flowfloat.rb
class Flowfloat < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/flowint.rb
class Flowint < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/flowtext.rb
class Flowtext < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/grant.rb
class Grant < ApplicationRecord
  belongs_to :user
  belongs_to :flowtemplate
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :flow
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :grants
  belongs_to :basesector, optional: true
  belongs_to :unionsector, optional: true
  belongs_to :basesector, optional: true
  has_many :usergroups
  has_many :opinions
  has_many :feedbacks
  has_and_belongs_to_many :usergroups
  has_many :userbusinadmins
  has_many :userfeedadmins
  has_secure_password
end

app/models/usergroup.rb
class Usergroup < ApplicationRecord
  has_and_belongs_to_many :auths
  has_and_belongs_to_many :users
end

app/models/wordattch.rb
class Wordattch < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordcoin.rb
class Wordcoin < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordint.rb
class Wordint < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordtext.rb
class Wordtext < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordtype.rb
class Wordtype < ApplicationRecord
  belongs_to :flowdef
  belongs_to :wordtypedef, optional: true
  default_scope { order('corder') }
end

app/controllers/clas_controller.rb
class ClasController < ApplicationController
  before_action :set_cla, only: [:show, :edit, :update, :destroy]

  def index
    @clas = Cla.all
  end

  def show
  end

  def new
    @cla = Cla.new
  end

  def edit
  end

  def create
    @cla = Cla.new(cla_params)
    respond_to do |format|
      if @cla.save
        format.html { redirect_to clas_path, notice: 'Cla was successfully created.' }
        format.json { render :show, status: :created, location: @cla }
      else
        format.html { render :new }
        format.json { render json: @cla.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cla.update(cla_params)
        format.html { redirect_to clas_path, notice: 'Cla was successfully updated.' }
        format.json { render :show, status: :ok, location: @cla }
      else
        format.html { render :edit }
        format.json { render json: @cla.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cla.destroy
    respond_to do |format|
      format.html { redirect_to clas_path, notice: 'Cla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cla
    @cla = Cla.find(params[:id])
  end

  def cla_params
    params.require(:cla).permit(:name)
  end
end

app/helpers/clas_helper.rb
module ClasHelper
end

app/views/clas/_form.html.erb
<div class="alert alert-block alert-success" style="display:none;">
  <button type="button" class="close" data-dismiss="alert">
    <i class="icon-remove"></i>
  </button>

  <p>
    <strong>
      <i class="icon-ok"></i>
    </strong>
    保存成功
  </p>

</div>

<%= form_with(model:cla,local:true,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
    <h3 class="header smaller lighter blue">
职能分类
      <small></small>
    </h3>
    <div class="form-group">
      <label class="col-sm-2 control-label no-padding-right" for="form-field-1"> 职能分类 </label>
      <div class="col-sm-10">
        <%= f.text_field :name,class:"col-xs-10 col-sm-8" %>
      </div>
    </div>

    <div class="clearfix form-actions">
      <div class="col-md-offset-2 col-md-10">
        <button type="submit" name="commit" value="保存" class="btn btn-info" data-disable-with="保存" id="submit">
          <i class="icon-ok bigger-110"></i>
          保存
        </button>

      </div>
    </div>
<% end %>

app/views/clas/edit.html.erb
<%= render 'layerbegin' %>
<div class="page-content">


  <div class="row">
    <div class="col-xs-12">
      <%= render 'form', cla: @cla %>
    </div>
  </div>
</div>
<%= render 'layerend' %>

app/views/clas/index.html.erb
<%= render 'layerbegin' %>

<div class="page-content">
  <div class="page-header">
    <h1>
      职能分类
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->

      <div class="row">
        <div class="col-xs-12">
          <div class="table-responsive">
            <table id="sample-table-1" class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th class="text-center">职能名称</th>
                <th class="text-center" width="150px">操作</th>
              </tr>
              </thead>
              <tbody>
              <% @clas.each do |cla| %>
                  <tr>
                    <td>
                      <%= cla.name %>
                    </td>
                    <td>
                      <div class="visible-md visible-lg hidden-sm hidden-xs btn-group" data-turbolinks="false">
                        <a class="btn btn-xs btn-primary" href=<%= edit_cla_path(cla) %>>
                          <i class="fa fa-edit bigger-120"></i>
                          编辑
                        </a>
                        <a data-confirm="确认删除?" data-method="delete" class="btn btn-xs btn-danger" href=<%= cla_path(cla) %>>
                          <i class="fa fa-trash bigger-120"></i>
                          删除
                        </a>
                      </div>
                    </td>

                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="clearfix form-actions">
        <div class="col-md-12 text-right" data-turbolinks="false">
          <a class="btn btn-info" href=<%= new_cla_path %>>
            <i class="fa fa-plus bigger-110"></i>
            新增
          </a>
        </div>
      </div>






<%= render 'layerend' %>

app/views/clas/new.html.erb
<%= render 'layerbegin' %>
<div class="page-content">


  <div class="row">
    <div class="col-xs-12">
      <%= render 'form', cla: @cla %>
    </div>
  </div>
</div>
<%= render 'layerend' %>