config/routes.rb
Rails.application.routes.draw do
  get 'basesectors/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'logins#index'
  resources :dealts
  resources :clas
  resources :unionsectors do
    collection do
      post 'get_user_list'
    end
  end
  resources :basesectors do
    collection do
      post 'get_user_list'
    end
  end
  resources :users do
    collection do
      get 'checkuser'
      get 'checkauth'
    end
  end
  resources :flowtemplates
  resources :flowdefs do
    member do
       get 'del_wordtype'
      get 'up_wordtype'
      get 'down_wordtype'
    end
  end
  resources :flows do
    collection do
      post 'uploadfile'
      get 'get_attachments'
      get 'del_attachment'
    end
  end
  resources :logins do
    collection do
      get 'logout'
    end
  end
  resources :modpwds
  resources :usergroups
  resources :myflows
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :flowattachment
  has_attached_file :attachment, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :attachment
end

app/models/auth.rb
class Auth < ApplicationRecord
  has_and_belongs_to_many :usergroups
end

app/models/basesector.rb
class Basesector < ApplicationRecord
  has_many :users
end

app/models/cla.rb
class Cla < ApplicationRecord
  has_many :flowtemplates
  has_many :unionsectors
end

app/models/dropdown.rb
class Dropdown < ApplicationRecord
  has_many :dropdownoptions
  belongs_to :flowtemplate
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :flow
  belongs_to :user
end

app/models/flow.rb
class Flow < ApplicationRecord
  has_many :flowdetails
  belongs_to :flowdef,optional: true
  has_many :flowfloats
  has_many :flowstrings
  has_many :flowtexts
  has_many :flowattachments
  has_many :flowints
  has_many :opinions
  has_many :feedbacks
  accepts_nested_attributes_for :feedbacks, allow_destroy: true
end

app/models/flowdef.rb
class Flowdef < ApplicationRecord
  has_many :wordtypes
  accepts_nested_attributes_for :wordtypes, allow_destroy: true
  has_many :flows
  belongs_to :unionsector
end

app/models/flowdetail.rb
class Flowdetail < ApplicationRecord
  belongs_to :flow
  has_many :flowfloats
  has_many :flowstrings
  has_many :flowtexts
  has_many :flowattachments
  has_many :flowints
end

app/models/flowfloat.rb
class Flowfloat < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/flowint.rb
class Flowint < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/flowtext.rb
class Flowtext < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/grant.rb
class Grant < ApplicationRecord
  belongs_to :user
  belongs_to :flowtemplate
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :flow
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :grants
  belongs_to :basesector, optional: true
  belongs_to :unionsector, optional: true
  belongs_to :basesector, optional: true
  has_many :usergroups
  has_many :opinions
  has_many :feedbacks
  has_and_belongs_to_many :usergroups
  has_many :userbusinadmins
  has_many :userfeedadmins
  has_secure_password
end

app/models/usergroup.rb
class Usergroup < ApplicationRecord
  has_and_belongs_to_many :auths
  has_and_belongs_to_many :users
end

app/models/wordattch.rb
class Wordattch < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordcoin.rb
class Wordcoin < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordint.rb
class Wordint < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordtext.rb
class Wordtext < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordtype.rb
class Wordtype < ApplicationRecord
  belongs_to :flowdef
  belongs_to :wordtypedef, optional: true
  default_scope { order('corder') }
end

app/controllers/flowdefs_controller.rb
class FlowdefsController < ApplicationController
  before_action :set_flowdef, only: [:show, :edit, :update, :destroy]

  def index
    @flowdefs = Flowdef.all
  end

  def show
  end

  def new
    @flowdef = Flowdef.create(status:0)
    redirect_to edit_flowdef_path(@flowdef)
  end

  def edit
    @wordtypes = @flowdef.wordtypes
    @wordtype = @flowdef.wordtypes.build

    #@wordtype = @flowdef.wordtypes.build
  end

  def create
    @flowtemplate = Flowtemplate.new(flowtemplate_params)
    respond_to do |format|
      if @flowtemplate.save
        format.html { redirect_to flowtemplates_path, notice: 'Flowtemplate was successfully created.' }
        format.json { render :show, status: :created, location: @flowtemplate }
      else
        format.html { render :new }
        format.json { render json: @flowtemplate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @flowdef.update(flowdef_params)
        wordtypes = @flowdef.wordtypes
        wordtypes.each do |f|
          if !f.corder
            f.corder = f.id
            f.save
          end
          if !f.wordtypedef_id
            f.destroy
          end
        end

        #@flowdef.wordtypes.create(wordtypedef_id:params[:wordtypes][:wordtypedef_id], name:params[:wordtypes][:name])
        format.html { redirect_to edit_flowdef_path(@flowdef), notice: 'Flowdef was successfully updated.' }
        format.json { render :show, status: :ok, location: @flowdef }
      else
        format.html { render :edit }
        format.json { render json: @flowdef.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flowdef.destroy
    respond_to do |format|
      format.html { redirect_to flowdefs_path, notice: 'Flowdef was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def del_wordtype
    @flowdef = Flowdef.find(params[:id])
    wordtype = Wordtype.find(params[:format])
    wordtype.destroy
    redirect_to edit_flowdef_path(@flowdef)
  end

  def up_wordtype
    wordtype = Wordtype.find(params[:format])
    prev_wordtype = Wordtype.where("corder < ?",wordtype.corder).order('corder').last
    if prev_wordtype
      corder = wordtype.corder
      wordtype.corder = prev_wordtype.corder
      prev_wordtype.corder = corder
      wordtype.save
      prev_wordtype.save
    end
    @flowdef = params[:id]
    redirect_to edit_flowdef_path(@flowdef)
  end

  def down_wordtype
    wordtype = Wordtype.find(params[:format])
    prev_wordtype = Wordtype.where("corder > ?",wordtype.corder).order('corder').first
    if prev_wordtype
      corder = wordtype.corder
      wordtype.corder = prev_wordtype.corder
      prev_wordtype.corder = corder
      wordtype.save
      prev_wordtype.save
    end
    @flowdef = params[:id]
    redirect_to edit_flowdef_path(@flowdef)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_flowdef
    @flowdef = Flowdef.find(params[:id])
  end

  def flowdef_params
    params.require(:flowdef).permit(:cla_id, :name, :summary, :status, :unionsector_id, wordtypes_attributes:[:wordtypedef_id, :name, :isnull, :nullsummary, :id, :_destroy])
  end
end

app/helpers/flowdefs_helper.rb
module FlowdefsHelper
end

app/views/flowdefs/_wordtypeform.html.erb

<div class="col-sm-1"></div>
<div class="col-sm-10" style="background: white;">

  <div>
    <div class="widget-box transparent">
      <div class="widget-header widget-header-small">
        <h4 class="blue smaller">
          <i class="fa fa-bars orange"></i>
          字段
        </h4>

        <div class="widget-toolbar action-buttons">
          <a href="#" data-action="reload">
            <i class="icon-refresh blue"></i>
          </a>

          &nbsp;
          <a href="#" class="pink">
            <i class="icon-trash"></i>
          </a>
        </div>
      </div>

      <div class="widget-body" style="background: white;">
        <div class="widget-main padding-8">
          <div id="profile-feed-1" class="profile-feed">










            <div class="profile-activity clearfix">

              <%= fields_for :wordtypes do |wordtype| %>
                <%= wordtype.select :wordtypedef_id,Wordtypedef.all.map{|n| [n.wordtype,n.id]}, {include_blank: '字段类型'},{class:'col-md-2',style:'height:28px;'} %>
                <%= wordtype.text_field :name,class:'col-md-2' %>
                <div class="checkbox col-md-1 text-right" style="padding-top: 0px;">
                  <label>
                    <%= wordtype.check_box :isnull,class:"ace" %>
                    <span class="lbl"> 非空</span>
                  </label>
                </div>
                <%= wordtype.text_field :nullsummary,placeholder:'非空描述',class:'col-md-4' %>
              <% end %>

            </div>



          </div>
        </div>
      </div>
    </div>
  </div>






</div>
<div class="col-sm-1" style="background: white;"></div>

app/views/flowdefs/edit.html.erb
<%= render 'layerbegin' %>
<div class="page-content" style="background: white;">


  <div class="row">
    <div class="col-xs-12">
      <div class="alert alert-block alert-success" style="display:none;">
        <button type="button" class="close" data-dismiss="alert">
          <i class="icon-remove"></i>
        </button>

        <p>
          <strong>
            <i class="icon-ok"></i>
          </strong>
          保存成功
        </p>

      </div>

      <%= form_with(model:@flowdef,local:true,id:'validation-form',:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
        <h3 class="header smaller lighter blue">
          定义流程
          <small></small>
        </h3>

        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-right" for="form-field-1"> 审批部门 </label>
          <div class="col-sm-10">
            <%= f.select :unionsector_id,Unionsector.all.map{|p| [p.name,p.id]},{include_blank:'请选择申批部门'},class:"col-xs-10 col-sm-8" %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-right" for="form-field-1"> 流程名称 </label>
          <div class="col-sm-10">
            <%= f.text_field :name,class:"col-xs-10 col-sm-8" %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-right" for="form-field-1">  </label>
          <div class="col-sm-10">
            <div class="checkbox" style="padding-top: 0px;padding-left: 0px;">
              <label>
                <%= f.check_box :status,class:"ace" %>
                <span class="lbl"> 启用</span>
              </label>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-right" for="form-field-1"> 描述 </label>
          <div class="col-sm-10">
            <%= f.text_area :summary,class:"col-xs-10 col-sm-8" %>
          </div>
        </div>

        <div class="hr hr32 hr-dotted"></div>

        <div id="wordtypediv">

          <!-- wordtypeform -->

          <div class="col-sm-1"></div>
          <div class="col-sm-10" style="background: white;">

            <div>
              <div class="widget-box transparent">
                <div class="widget-header widget-header-small">
                  <h4 class="blue smaller">
                    <i class="fa fa-bars orange"></i>
                    字段
                  </h4>

                  <div class="widget-toolbar action-buttons">

                  </div>
                </div>

                <div class="widget-body" style="background: white;">
                  <div class="widget-main padding-8">
                    <div id="profile-feed-1" class="profile-feed">



                      <%= f.fields_for :wordtypes do |wordtype| %>
                        <div class="profile-activity clearfix">
                          <%= wordtype.select :wordtypedef_id,Wordtypedef.all.map{|n| [n.wordtype,n.id]}, {include_blank: '字段类型'},{class:'col-md-2',style:'height:28px;'} %>
                          <%= wordtype.text_field :name,class:'col-md-3',placeholder:'字段名称' %>
                          <div class="checkbox col-md-2 text-right" style="padding-top: 0px;">
                            <label>
                              <%= wordtype.check_box :isnull,class:"ace" %>
                              <span class="lbl"> 非空</span>
                            </label>
                          </div>
                          <%= wordtype.text_field :nullsummary,placeholder:'非空描述',class:'col-md-4' %>

                          <div class="tools action-buttons">

                            <% if wordtype.object.id %>

                              <table>
                                <tr>
                                  <td>
                                    <div class="spinner-buttons input-group-btn">
                                      <a href=<%= up_wordtype_flowdef_path(@flowdef,wordtype.object) %> >
                                        <button type="button" class="btn spinner-up btn-xs btn-link" style="padding: 0px 4px!important;height: 22px;margin-top: 0px;margin-left: -4px;">
                                          <i class="icon-caret-up"></i>
                                        </button>
                                      </a>
                                      <a href= <%= down_wordtype_flowdef_path(@flowdef,wordtype.object) %> >
                                        <button type="button" class="btn spinner-down btn-xs btn-link" style="padding: 0px 4px!important;height: 22px;margin-top: 0px;margin-right: 1px;margin-left: -4px;">
                                          <i class="icon-caret-down"></i>
                                        </button>
                                      </a>
                                    </div>
                                  </td>
                                  <td>
                                    <a href=<%= del_wordtype_flowdef_path(@flowdef,wordtype.object) %> class="red">
                                      <i class="icon-remove bigger-125"></i>
                                    </a>
                                  </td>
                            <% end %>
                            </tr>
                            </table>

                          </div>

                        </div>



                      <% end %>

                    </div>
                  </div>
                </div>
              </div>
            </div>






          </div>
          <div class="col-sm-1" style="background: white;"></div>
<%#= render 'wordtypeform' %>
          <!-- wordtypeform_end -->
        </div>
        <div class=" form-actions" style="background: white;border-top: 0px;">
          <div class="col-md-offset-2 col-md-10">
            <button type="submit" name="commit" value="保存" class="btn btn-info" data-disable-with="保存" id="submit">
              <i class="icon-ok bigger-110"></i>
              保存
            </button>

          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
    $('#validation-form').validate({
        debug: false,
        errorElement: 'div',
        errorClass: 'help-block',
        focusInvalid: false,
        rules: {
            'flowdef[unionsector_id]': {
                required: true
            },
            'flowdef[name]': {
                required: true
            }
        },

        messages: {
            'flowdef[unionsector_id]': {
                required: "&nbsp;&nbsp;审批部门不能为空"
            },
            'flowdef[name]': {
                required: "&nbsp;&nbsp;流程名称不能为空"
            }
        },

        invalidHandler: function (event, validator) { //display error alert on form submit
            $('.alert-danger', $('.login-form')).show();
        },

        highlight: function (e) {
            $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
        },

        success: function (e) {
            $(e).closest('.form-group').removeClass('has-error').addClass('has-info');
            $(e).remove();
        }
    });
</script>
<%= render 'layerend' %>

app/views/flowdefs/index.html.erb
<%= render 'layerbegin' %>

<div class="page-content">
  <div class="page-header">
    <h1>
      定义流程
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->

      <div class="row">
        <div class="col-xs-12">
          <div class="table-responsive">
            <table id="sample-table-1" class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th class="text-center">流程名称</th>
                <th class="text-center">审批部门</th>
                <th class="text-center">状态</th>
                <th class="text-center" width="150px">操作</th>
              </tr>
              </thead>
              <tbody>
              <% @flowdefs.each do |flowdef| %>
                  <tr>

                    <td>
                      <%= flowdef.name %>
                    </td>
                    <td>
                      <% unionsector = flowdef.unionsector %>
                      <% if unionsector %>
                      <%= unionsector.name %>
                      <% end %>
                    </td>
                    <td>
                      <% if flowdef.status == 1 %>
                      <span class="blue">正常</span>
                        <% else %>
                      <span class="red">草稿</span>
                        <% end %>
                    </td>
                    <td>
                      <div class="visible-md visible-lg hidden-sm hidden-xs btn-group" data-turbolinks="false">
                        <a class="btn btn-xs btn-primary" href=<%= edit_flowdef_path(flowdef) %>>
                          <i class="fa fa-edit bigger-120"></i>
                          编辑
                        </a>
                        <a data-confirm="确认删除?" data-method="delete" class="btn btn-xs btn-danger" href=<%= flowdef_path(flowdef) %>>
                          <i class="fa fa-trash bigger-120"></i>
                          删除
                        </a>
                      </div>
                    </td>

                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="clearfix form-actions">
        <div class="col-md-12 text-right" data-turbolinks="false">
          <a class="btn btn-info" href=<%= new_flowdef_path %>>
            <i class="fa fa-plus bigger-110"></i>
            新增
          </a>
        </div>
      </div>






<%= render 'layerend' %>