config/routes.rb
Rails.application.routes.draw do
  get 'basesectors/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'logins#index'
  resources :dealts
  resources :clas
  resources :unionsectors do
    collection do
      post 'get_user_list'
    end
  end
  resources :basesectors do
    collection do
      post 'get_user_list'
    end
  end
  resources :users do
    collection do
      get 'checkuser'
      get 'checkauth'
    end
  end
  resources :flowtemplates
  resources :flowdefs do
    member do
       get 'del_wordtype'
      get 'up_wordtype'
      get 'down_wordtype'
    end
  end
  resources :flows do
    collection do
      post 'uploadfile'
      get 'get_attachments'
      get 'del_attachment'
    end
  end
  resources :logins do
    collection do
      get 'logout'
    end
  end
  resources :modpwds
  resources :usergroups
  resources :myflows
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :flowattachment
  has_attached_file :attachment, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :attachment
end

app/models/auth.rb
class Auth < ApplicationRecord
  has_and_belongs_to_many :usergroups
end

app/models/basesector.rb
class Basesector < ApplicationRecord
  has_many :users
end

app/models/cla.rb
class Cla < ApplicationRecord
  has_many :flowtemplates
  has_many :unionsectors
end

app/models/dropdown.rb
class Dropdown < ApplicationRecord
  has_many :dropdownoptions
  belongs_to :flowtemplate
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :flow
  belongs_to :user
end

app/models/flow.rb
class Flow < ApplicationRecord
  has_many :flowdetails
  belongs_to :flowdef,optional: true
  has_many :flowfloats
  has_many :flowstrings
  has_many :flowtexts
  has_many :flowattachments
  has_many :flowints
  has_many :opinions
  has_many :feedbacks
  accepts_nested_attributes_for :feedbacks, allow_destroy: true
end

app/models/flowdef.rb
class Flowdef < ApplicationRecord
  has_many :wordtypes
  accepts_nested_attributes_for :wordtypes, allow_destroy: true
  has_many :flows
  belongs_to :unionsector
end

app/models/flowfloat.rb
class Flowfloat < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/flowint.rb
class Flowint < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/flowtext.rb
class Flowtext < ApplicationRecord
  belongs_to :flowdetail,optional: true
  belongs_to :flow
end

app/models/grant.rb
class Grant < ApplicationRecord
  belongs_to :user
  belongs_to :flowtemplate
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :flow
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :grants
  belongs_to :basesector, optional: true
  belongs_to :unionsector, optional: true
  belongs_to :basesector, optional: true
  has_many :usergroups
  has_many :opinions
  has_many :feedbacks
  has_and_belongs_to_many :usergroups
  has_many :userbusinadmins
  has_many :userfeedadmins
  has_secure_password
end

app/models/usergroup.rb
class Usergroup < ApplicationRecord
  has_and_belongs_to_many :auths
  has_and_belongs_to_many :users
end

app/models/wordattch.rb
class Wordattch < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordcoin.rb
class Wordcoin < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordint.rb
class Wordint < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordtext.rb
class Wordtext < ApplicationRecord
  belongs_to :flowtemplate
end

app/models/wordtype.rb
class Wordtype < ApplicationRecord
  belongs_to :flowdef
  belongs_to :wordtypedef, optional: true
  default_scope { order('corder') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def check_auth
    if !session[:login]
      redirect_to logins_path
    end
  end
end

app/views/application/_layerbegin.html.erb
<div class="navbar navbar-default" id="navbar">
  <script type="text/javascript">
      try{ace.settings.check('navbar' , 'fixed')}catch(e){}

      $(document).ready(function(){

      });
  </script>

  <% url = request.path_parameters['controller'] %>
  <div class="navbar-container" id="navbar-container">
    <div class="navbar-header pull-left">
      <a href="#" class="navbar-brand">
        <small>
          <i class="fa fa-bars"></i>
          呈贡信用社
        </small>
      </a><!-- /.brand -->
    </div><!-- /.navbar-header -->

    <div class="navbar-header pull-right" role="navigation">
      <ul class="nav ace-nav">
        <li class="red">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-bell-alt icon-animated-bell"></i>
            <span class="badge badge-important"></span>
          </a>



          <ul class="pull-right dropdown-navbar  dropdown-menu dropdown-caret dropdown-close">
            <li class="dropdown-header">
              <i class="icon-warning-sign"></i>
              待处理
            </li>



          </ul>
        </li>

        <li class="light-blue">
          <a data-toggle="dropdown" href="#" class="dropdown-toggle">

								<span class="user-info">
									<small>欢迎光临</small>
<%= session[:username] %>
								</span>

            <i class="icon-caret-down"></i>
          </a>

          <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
            <li data-turbolinks="false">
              <a href=<%= modpwds_path %>>
                <i class="icon-cog"></i>
                修改密码
              </a>
            </li>

            <li class="divider"></li>

            <li>
              <a href=<%= logout_logins_path %>>
                <i class="icon-off"></i>
                退出
              </a>
            </li>
          </ul>
        </li>
      </ul><!-- /.ace-nav -->
    </div><!-- /.navbar-header -->
  </div><!-- /.container -->
</div>

<div class="main-container" id="main-container">
  <script type="text/javascript">
      try{ace.settings.check('main-container' , 'fixed')}catch(e){}
  </script>

  <div class="main-container-inner">
    <a class="menu-toggler" id="menu-toggler" href="#">
      <span class="menu-text"></span>
    </a>

    <div class="sidebar" id="sidebar">
      <script type="text/javascript">
          try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
      </script>

      <% url = request.url %>

      <ul class="nav nav-list">
        <li class="active" data-turbolinks="false">
          <a href="#">
            <i class="icon-dashboard"></i>
            <span class="menu-text"> 控制台 </span>
          </a>
        </li>

<% if url.include?('clas') || url.include?('flowdefs') || url.include?('usergroups') %>
        <li class="active">
          <% else %>
          <li>
            <% end %>
          <a href="#" class="dropdown-toggle">
            <i class="icon-cog"></i>
            <span class="menu-text"> 系统 </span>
            <b class="arrow icon-angle-down"></b>
          </a>
          <ul class="submenu">
            <li data-turbolinks="false">
              <a href=<%= clas_path %>>
                <i class="icon-double-angle-right"></i>
                职能分类
              </a>
            </li>
            <li data-turbolinks="false">
              <a href=<%= flowdefs_path %>>
                <i class="icon-double-angle-right"></i>
                定义流程模板
              </a>
            </li>
            <li data-turbolinks="false">
              <a href=<%= usergroups_path %>>
                <i class="icon-double-angle-right"></i>
                权限
              </a>
            </li>
          </ul>
        </li>
<% if url.include?('unionsectors') || url.include?('basesectors') || url.include?('users') %>
        <li class="active">
          <% else %>
          <li>
            <% end %>
          <a href="#" class="dropdown-toggle">
            <i class="icon-sitemap"></i>
            <span class="menu-text"> 机构架构 </span>
            <b class="arrow icon-angle-down"></b>
          </a>
          <ul class="submenu">
            <li data-turbolinks="false">
              <a href=<%= unionsectors_path %>>
                <i class="icon-double-angle-right"></i>
                部门
              </a>
            </li>
            <li data-turbolinks="false">
              <a href=<%= basesectors_path %>>
                <i class="icon-double-angle-right"></i>
                基社
              </a>
            </li>
          </ul>
        </li>
<% if url.include?('flows') %>
        <li class="active">
          <% else %>
        <li>
          <% end %>
          <a href="#" class="dropdown-toggle">
            <i class="icon-exchange"></i>
            <span class="menu-text"> 工作申报 </span>
            <b class="arrow icon-angle-down"></b>
          </a>
          <ul class="submenu">
            <li data-turbolinks="false">
              <a href=<%= myflows_path %>>
                <i class="icon-double-angle-right"></i>
                待办工作
              </a>
            </li>
            <li data-turbolinks="false">
              <a href=<%= flows_path %>>
                <i class="icon-double-angle-right"></i>
                新建工作
              </a>
            </li>
          </ul>
        </li>

      </ul><!-- /.nav-list -->

      <div class="sidebar-collapse" id="sidebar-collapse">
        <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
      </div>

      <script type="text/javascript">
          ace.demo.init();
// if(!"ace" in window) {
//     jQuery(function (a) {
//         ace.handle_side_menu(jQuery);
//         ace.enable_search_ahead(jQuery);
//         ace.general_things(jQuery);
//         ace.widget_boxes(jQuery);
//         ace.widget_reload_handler(jQuery)
//     });
// }

          try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
      </script>
    </div>

    <div class="main-content">